name: "sast-scan"
description: "This action wraps the [oss sast](https://github.com/AppThreat/sast-scan/) scanning tool called `sast-scan`."
inputs:
  src:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: "/github/workspace"
  output:
    description: "Output directory for the generated reports. Defaults to reports"
    required: false
    default: "/github/workspace/reports"
  type:
    description: "Project type. Eg: java, python, nodejs"
    required: true
runs:
  using: "docker"
  image: "docker://quay.io/appthreat/sast-scan:latest"
  args:
    - "scan"
    - "--src"
    - ${{ inputs.src }}
    - "--out_dir"
    - ${{ inputs.output }}
    - "--type"
    - ${{ inputs.type }}
branding:
  icon: "check"
  color: "blue"
