name: "sast-scan"
description: "This action wraps the [oss sast](https://github.com/AppThreat/sast-scan/) scanning tool called `sast-scan`. sast-scan supports a range of free and open source SAST scanners and comes with optimal configurations for various languages and frameworks."
inputs:
  src:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: $GITHUB_WORKSPACE
  output:
    description: "Output directory for the generated reports. Defaults to reports"
    required: false
    default: reports
  type:
    description: "Project type. Eg: java, python, nodejs"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--src"
    - ${{ inputs.src }}
    - "--out_dir"
    - ${{ inputs.output }}
    - "--type"
    - ${{ inputs.type }}
branding:
  icon: "check"
  color: "blue"
